version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: scentrise-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scentrise
    volumes:
      - mongo_data:/data/db
    networks:
      - scentrise-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: scentrise-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/scentrise
      - JWT_SECRET=your-super-secret-jwt-key
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - scentrise-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: scentrise-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - scentrise-network

volumes:
  mongo_data:

networks:
  scentrise-network:
    driver: bridge
