import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import { Product } from '../models/Product';
import { env } from '../config/env';

const sampleProducts = [
  // Men's Fragrances
  {
    title: "Dior Sauvage Eau de Toilette",
    slug: "dior-sauvage-edt",
    brand: "Dior",
    gender: "men",
    family: "woody",
    notes: ["Bergamot", "Sichuan Pepper", "Lavender", "Ambroxan", "Cedar"],
    description: "A radically fresh composition, dictated by a name that has the ring of a manifesto. A composition that reveals fresh and noble notes, that plays with fire without being burned.",
    price: 8500,
    mrp: 10000,
    images: [{ url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500" }],
    stock: 25,
    ratingAvg: 4.5,
    ratingCount: 128,
    isFeatured: true,
  },
  {
    title: "Bleu de Chanel Eau de Parfum",
    slug: "bleu-de-chanel-edp",
    brand: "Chanel",
    gender: "men",
    family: "woody",
    notes: ["Grapefruit", "Lemon", "Mint", "Pink Pepper", "Cedar", "Sandalwood"],
    description: "An aromatic-woody fragrance that opens up new perspectives. A timeless scent housed in a bottle of a deep and mysterious blue.",
    price: 12000,
    mrp: 14500,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 18,
    ratingAvg: 4.6,
    ratingCount: 156,
    isFeatured: true,
  },
  {
    title: "Creed Aventus",
    slug: "creed-aventus",
    brand: "Creed",
    gender: "men",
    family: "woody",
    notes: ["Pineapple", "Blackcurrant", "Apple", "Bergamot", "Rose", "Birch", "Musk"],
    description: "A sophisticated scent perfect for the confident, modern man. Inspired by the dramatic life of a historic emperor.",
    price: 22000,
    mrp: 25000,
    images: [{ url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=500" }],
    stock: 8,
    ratingAvg: 4.8,
    ratingCount: 89,
    isFeatured: true,
  },
  {
    title: "Acqua di Gio Pour Homme",
    slug: "acqua-di-gio-pour-homme",
    brand: "Giorgio Armani",
    gender: "men",
    family: "fresh",
    notes: ["Bergamot", "Neroli", "Green Tangerine", "Marine Notes", "Jasmine", "Cedar"],
    description: "Inspired by the fresh sea breeze, this fragrance captures the pure freshness and warmth of the Mediterranean Sea.",
    price: 7500,
    mrp: 9000,
    images: [{ url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=500" }],
    stock: 30,
    ratingAvg: 4.3,
    ratingCount: 95,
    isFeatured: true,
  },
  {
    title: "Versace Eros",
    slug: "versace-eros",
    brand: "Versace",
    gender: "men",
    family: "oriental",
    notes: ["Mint", "Green Apple", "Lemon", "Tonka Bean", "Geranium", "Vanilla"],
    description: "A fragrance for a strong, passionate man who is master of himself. Eros interprets the sublime masculine through a luminous aura.",
    price: 6500,
    mrp: 8000,
    images: [{ url: "https://images.unsplash.com/photo-1594736797933-d0d39732d5d5?w=500" }],
    stock: 22,
    ratingAvg: 4.2,
    ratingCount: 134,
    isFeatured: false,
  },
  {
    title: "Jean Paul Gaultier Le Male",
    slug: "jpg-le-male",
    brand: "Jean Paul Gaultier",
    gender: "men",
    family: "oriental",
    notes: ["Lavender", "Mint", "Cardamom", "Cinnamon", "Vanilla", "Sandalwood"],
    description: "The most seductive male fragrance. A fresh oriental with lavender, vanilla and sandalwood.",
    price: 5500,
    mrp: 7000,
    images: [{ url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=500" }],
    stock: 35,
    ratingAvg: 4.4,
    ratingCount: 112,
    isFeatured: false,
  },
  {
    title: "Paco Rabanne 1 Million",
    slug: "paco-rabanne-1-million",
    brand: "Paco Rabanne",
    gender: "men",
    family: "oriental",
    notes: ["Blood Mandarin", "Grapefruit", "Mint", "Rose", "Cinnamon", "Leather"],
    description: "An absolutely fresh fragrance distinguished by its radiant, sophisticated, and dazzling signature.",
    price: 6000,
    mrp: 7500,
    images: [{ url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500" }],
    stock: 28,
    ratingAvg: 4.1,
    ratingCount: 98,
    isFeatured: false,
  },
  {
    title: "Calvin Klein Eternity for Men",
    slug: "ck-eternity-men",
    brand: "Calvin Klein",
    gender: "men",
    family: "fresh",
    notes: ["Mandarin", "Bergamot", "Sage", "Basil", "Geranium", "Sandalwood"],
    description: "A timeless essence of masculinity. Classic, refined, and enduring.",
    price: 4500,
    mrp: 6000,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 40,
    ratingAvg: 4.0,
    ratingCount: 87,
    isFeatured: false,
  },

  // Women's Fragrances
  {
    title: "Chanel No. 5 Eau de Parfum",
    slug: "chanel-no-5-edp",
    brand: "Chanel",
    gender: "women",
    family: "floral",
    notes: ["Neroli", "Ylang-ylang", "Rose", "Jasmine", "Sandalwood", "Vanilla"],
    description: "The essence of femininity. A bouquet of abstracted flowers. A woman's perfume with a woman's scent.",
    price: 12000,
    mrp: 14000,
    images: [{ url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500" }],
    stock: 15,
    ratingAvg: 4.8,
    ratingCount: 89,
    isFeatured: true,
  },
  {
    title: "Dior Miss Dior Eau de Parfum",
    slug: "dior-miss-dior-edp",
    brand: "Dior",
    gender: "women",
    family: "floral",
    notes: ["Blood Orange", "Mandarin", "Pink Pepper", "Rose", "Peony", "Patchouli"],
    description: "A declaration of love. A floral fragrance that expresses tenderness and lightness with an explosion of fresh and vibrant notes.",
    price: 10500,
    mrp: 12500,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 20,
    ratingAvg: 4.7,
    ratingCount: 145,
    isFeatured: true,
  },
  {
    title: "Viktor & Rolf Flowerbomb",
    slug: "viktor-rolf-flowerbomb",
    brand: "Viktor & Rolf",
    gender: "women",
    family: "floral",
    notes: ["Tea", "Bergamot", "Freesia", "Orchid", "Rose", "Jasmine", "Patchouli"],
    description: "An explosive bouquet of flowers that has the power to make everything seem more positive.",
    price: 11000,
    mrp: 13000,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 20,
    ratingAvg: 4.6,
    ratingCount: 73,
    isFeatured: true,
  },
  {
    title: "Marc Jacobs Daisy",
    slug: "marc-jacobs-daisy",
    brand: "Marc Jacobs",
    gender: "women",
    family: "floral",
    notes: ["Wild Berries", "Grapefruit", "Violet Leaves", "Jasmine", "Gardenia", "White Woods"],
    description: "A fragrance that is charming, whimsical, and flirty. Fresh and feminine with its soft florals.",
    price: 7000,
    mrp: 8500,
    images: [{ url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500" }],
    stock: 32,
    ratingAvg: 4.3,
    ratingCount: 126,
    isFeatured: false,
  },
  {
    title: "Lancôme La Vie Est Belle",
    slug: "lancome-la-vie-est-belle",
    brand: "Lancôme",
    gender: "women",
    family: "gourmand",
    notes: ["Blackcurrant", "Pear", "Iris", "Jasmine", "Orange Blossom", "Vanilla"],
    description: "A unique olfactory signature created by three of France's leading perfumers. Life is beautiful!",
    price: 9500,
    mrp: 11000,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 25,
    ratingAvg: 4.5,
    ratingCount: 178,
    isFeatured: true,
  },
  {
    title: "Yves Saint Laurent Black Opium",
    slug: "ysl-black-opium",
    brand: "Yves Saint Laurent",
    gender: "women",
    family: "oriental",
    notes: ["Pink Pepper", "Orange Blossom", "Pear", "Coffee", "Jasmine", "Vanilla"],
    description: "The most addictive fragrance. A seductive and mysterious scent with coffee and vanilla notes.",
    price: 9000,
    mrp: 10500,
    images: [{ url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500" }],
    stock: 18,
    ratingAvg: 4.4,
    ratingCount: 203,
    isFeatured: true,
  },
  {
    title: "Gucci Bloom",
    slug: "gucci-bloom",
    brand: "Gucci",
    gender: "women",
    family: "floral",
    notes: ["Natural Tuberose", "Jasmine", "Rangoon Creeper"],
    description: "A rich white floral fragrance. An authentic scent full of flowers from a garden where they can be seen in bloom.",
    price: 8500,
    mrp: 10000,
    images: [{ url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?w=500" }],
    stock: 22,
    ratingAvg: 4.2,
    ratingCount: 94,
    isFeatured: false,
  },
  {
    title: "Dolce & Gabbana Light Blue",
    slug: "dg-light-blue",
    brand: "Dolce & Gabbana",
    gender: "women",
    family: "citrus",
    notes: ["Sicilian Lemon", "Apple", "Bluebells", "Bamboo", "Jasmine", "Cedar"],
    description: "Inspired by the joy of life, the pure sky, and the deep sea. Fresh, floral, and feminine.",
    price: 6500,
    mrp: 8000,
    images: [{ url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500" }],
    stock: 38,
    ratingAvg: 4.1,
    ratingCount: 115,
    isFeatured: false,
  },

  // Unisex Fragrances
  {
    title: "Tom Ford Black Orchid",
    slug: "tom-ford-black-orchid",
    brand: "Tom Ford",
    gender: "unisex",
    family: "oriental",
    notes: ["Black Truffle", "Ylang-ylang", "Blackcurrant", "Black Orchid", "Dark Chocolate", "Patchouli"],
    description: "A luxurious and sensual fragrance of rich, dark accords and an alluring potion of black orchids and spice.",
    price: 15000,
    mrp: 18000,
    images: [{ url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=500" }],
    stock: 8,
    ratingAvg: 4.7,
    ratingCount: 56,
    isFeatured: true,
  },
  {
    title: "Maison Margiela REPLICA Jazz Club",
    slug: "maison-margiela-jazz-club",
    brand: "Maison Margiela",
    gender: "unisex",
    family: "woody",
    notes: ["Pink Pepper", "Primofiore Lemon", "Neroli", "Rum", "Vanilla", "Tobacco Leaf"],
    description: "The memory of a Brooklyn jazz club. The warm, enveloping scent of cigars, aged rum and smooth jazz.",
    price: 9500,
    mrp: 11500,
    images: [{ url: "https://images.unsplash.com/photo-1594736797933-d0d39732d5d5?w=500" }],
    stock: 12,
    ratingAvg: 4.4,
    ratingCount: 41,
    isFeatured: true,
  },
  {
    title: "Le Labo Santal 33",
    slug: "le-labo-santal-33",
    brand: "Le Labo",
    gender: "unisex",
    family: "woody",
    notes: ["Violet", "Cardamom", "Iris", "Papyrus", "Ambrox", "Sandalwood"],
    description: "A cult classic. Woody, smoky, and addictive. The sophisticated scent of the American West.",
    price: 18000,
    mrp: 21000,
    images: [{ url: "https://images.unsplash.com/photo-1594736797933-d0d39732d5d5?w=500" }],
    stock: 6,
    ratingAvg: 4.6,
    ratingCount: 73,
    isFeatured: true,
  },
  {
    title: "Byredo Gypsy Water",
    slug: "byredo-gypsy-water",
    brand: "Byredo",
    gender: "unisex",
    family: "woody",
    notes: ["Bergamot", "Lemon", "Pepper", "Incense", "Pine Needles", "Sandalwood"],
    description: "A fragrance built around the dream of the Romani culture. Woody and mysterious.",
    price: 16000,
    mrp: 19000,
    images: [{ url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=500" }],
    stock: 10,
    ratingAvg: 4.5,
    ratingCount: 62,
    isFeatured: false,
  },
  {
    title: "Diptyque Philosykos",
    slug: "diptyque-philosykos",
    brand: "Diptyque",
    gender: "unisex",
    family: "fresh",
    notes: ["Fig Leaves", "Fig Fruit", "Green Stems"],
    description: "The memory of a Greek summer. An ode to the entire fig tree: the green freshness of the leaves, the milky flavor of the figs.",
    price: 14000,
    mrp: 16500,
    images: [{ url: "https://images.unsplash.com/photo-1594736797933-d0d39732d5d5?w=500" }],
    stock: 14,
    ratingAvg: 4.3,
    ratingCount: 48,
    isFeatured: false,
  },
  {
    title: "Hermès Terre d'Hermès",
    slug: "hermes-terre-d-hermes",
    brand: "Hermès",
    gender: "unisex",
    family: "woody",
    notes: ["Orange", "Grapefruit", "Pepper", "Flint", "Geranium", "Cedar"],
    description: "A metaphor for raw materials and their metamorphosis. A novel that expresses the alchemical power of the elements.",
    price: 11500,
    mrp: 13500,
    images: [{ url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=500" }],
    stock: 16,
    ratingAvg: 4.4,
    ratingCount: 85,
    isFeatured: false,
  },

  // Affordable/Drugstore Options
  {
    title: "Davidoff Cool Water",
    slug: "davidoff-cool-water",
    brand: "Davidoff",
    gender: "men",
    family: "fresh",
    notes: ["Mint", "Lavender", "Coriander", "Sandalwood", "Musk", "Amber"],
    description: "The original fresh aquatic fragrance. Clean, crisp, and refreshing.",
    price: 3500,
    mrp: 4500,
    images: [{ url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=500" }],
    stock: 45,
    ratingAvg: 4.0,
    ratingCount: 167,
    isFeatured: false,
  },
  {
    title: "Adidas Team Five",
    slug: "adidas-team-five",
    brand: "Adidas",
    gender: "men",
    family: "fresh",
    notes: ["Lemon", "Bergamot", "Ginger", "Lavender", "Cedar", "Musk"],
    description: "A sporty and energetic fragrance for the active man. Fresh and invigorating.",
    price: 1200,
    mrp: 1800,
    images: [{ url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500" }],
    stock: 60,
    ratingAvg: 3.8,
    ratingCount: 89,
    isFeatured: false,
  },
  {
    title: "Fogg Scent Xpressio",
    slug: "fogg-scent-xpressio",
    brand: "Fogg",
    gender: "men",
    family: "fresh",
    notes: ["Citrus", "Marine", "Woody", "Musk"],
    description: "No gas, only perfume. Long-lasting fragrance for everyday wear.",
    price: 800,
    mrp: 1200,
    images: [{ url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=500" }],
    stock: 80,
    ratingAvg: 3.5,
    ratingCount: 234,
    isFeatured: false,
  },
  {
    title: "Engage Spell",
    slug: "engage-spell",
    brand: "Engage",
    gender: "women",
    family: "floral",
    notes: ["Fruity", "Floral", "Woody"],
    description: "Cast a spell with this enchanting fragrance. Perfect for daily wear.",
    price: 600,
    mrp: 900,
    images: [{ url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500" }],
    stock: 75,
    ratingAvg: 3.6,
    ratingCount: 156,
    isFeatured: false,
  },
  {
    title: "Wild Stone Code Titanium",
    slug: "wild-stone-code-titanium",
    brand: "Wild Stone",
    gender: "men",
    family: "woody",
    notes: ["Bergamot", "Lavender", "Geranium", "Sandalwood", "Musk"],
    description: "Decode your style with this masculine fragrance. Strong and confident.",
    price: 1000,
    mrp: 1500,
    images: [{ url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500" }],
    stock: 55,
    ratingAvg: 3.7,
    ratingCount: 198,
    isFeatured: false,
  }
];

async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert sample products
    const products = await Product.insertMany(sampleProducts);
    console.log(`Inserted ${products.length} sample products`);

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
